language: cpp
before_script:
  - sudo apt-get install libboost-test-dev -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libspdlog-dev -y
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T allocator.deb -unikita-chizh:$BINTRAY_API_KEY "https://api.bintray.com/content/nikita-chizh/Otus/allocator/$TRAVIS_BUILD_NUMBER/allocator.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"